[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PayU webhook will be added later

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*"]

# Fix for CORS issues with functions
[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Ensure assets are properly cached but HTML is not
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[dev]
  functions = "netlify/functions"
  publish = "dist"
  port = 8888
  autoLaunch = false